server: 
  port    : 1000
databseMaster:
  address : "localhost"
  db      : "db_mall_tangsel"
  user    : "jemmycalak"
  password: "jemmycalak"
databaseSlave:
  address : "localhost"
  user    : "jemmycalak"
  password: "jemmycalak"
redis:
  address : "localhost:6437"